### ISSUE TITLE
Fulfil the Open-Source Checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/conferl#1]
## General Items
- [x] It has a github repo
- [x] It has a proper LICENSE file
- [ ] It's has a clear and useful README.md
- [ ] It's documented (with examples)
- [ ] It's tested
- [x] It's hooked to a the [open-source hipchat room](https://www.hipchat.com/gpBpW3SsT)
- [ ] It has a link to the [open-source hipchat room](https://www.hipchat.com/gpBpW3SsT) in its README
- [ ] It has a link to [inaka.github.io](http://inaka.github.io) in its README and/or landing page

## Exhibition
- [ ] There is a blog post about it
- [ ] It's shared on social networks
- [ ] It's shared on reddit
- [ ] It's shared on hacker news with a title like Show HN: description
- [ ] It has a landing page built in github pages

## For Erlang Projects
- [x] It's checked with [Gadget](http://gadget.inakalabs.com)
- [ ] It's shared on [Erlang Central](http://erlangcentral.org/add-news/)
